import { ClerkProvider } from "@clerk/nextjs";
import "./globals.css";
import type { Metadata } from "next";
import { Inter } from "next/font/google";
import { Navbar } from "./navbar";
import { cn } from "~/lib/utils";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <ClerkProvider>
      <html lang="en">
        <body
          className={cn(
            "bg-slate-50 text-black min-h-screen flex flex-col gap-8",
            inter.className
          )}
        >
          <Navbar />
          <div className="container flex-1 px-4">{children}</div>
        </body>
      </html>
    </ClerkProvider>
  );
}
